concurrent = 10
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "URL do Gitlab"
  token = "Token do Gitlab"
  executor = "docker+machine"
  limit = 10
  clone_url = "URl do gitlab"
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.5"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
  [runners.machine]
    IdleCount = 1                    
    IdleTime = 40                  
    MaxBuilds = 3                    
    MachineName = "gitlab-runner-%s"    
    MachineDriver = "amazonec2"
    MachineOptions = [
      "amazonec2-access-key=AAA",
      "amazonec2-secret-key=AAA",
      "amazonec2-region=us-west-1",
      "amazonec2-zone=c",
      "amazonec2-vpc-id=vpc-AAA",
      "amazonec2-subnet-id=subnet-AAA",
      "amazonec2-security-group=NomeDoGRupo",
      "amazonec2-instance-type=t2.micro",
      "amazonec2-volume-type=gp3",
      "amazonec2-private-address-only=true",  # - You can configure the runner to run only private address, for security reasons.
      "amazonec2-tags=Example,Tag" # You can add tags in machine for organization.
    ]
    
    # You can set the times of autoscaling machines.
  [[runners.machine.autoscaling]]
    Periods = ["* * 8-11 * * mon-fri *"] # Every day of the week, between 8:00am and 11:59am, there will be an idle machine.
    IdleCount = 1
    IdleTime = 180
    Timezone = "America/Sao_Paulo"
  [[runners.machine.autoscaling]]
    Periods = ["* * 14-17 * * mon-fri *"] # Every day of the week, between 14:00pm and 17:59, there will be an idle machine.
    IdleCount = 1
    IdleTime = 180
    Timezone = "America/Sao_Paulo"
  [[runners.machine.autoscaling]]
    Periods = ["* * * * * sat,sun *"] # On weekends, there will be no idle machines.
    IdleCount = 0
    IdleTime = 60
    Timezone = "America/Sao_Paulo"
